[project]
name = "pr003"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "helainev", email = "polmast2@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
pr003 = "pr003:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
